(function(global){
 'use strict';let current=null;const cache=new Map();
 async function asset(src,col=0,row=0,cols=1,rows=1){
  const key=[src,col,row,cols,rows].join('|');if(cache.has(key))return cache.get(key);const img=new Image();img.src=src;await img.decode();const c=document.createElement('canvas');c.width=Math.floor(img.naturalWidth/cols);c.height=Math.floor(img.naturalHeight/rows);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,col*c.width,row*c.height,c.width,c.height,0,0,c.width,c.height);const a=ctx.getImageData(0,0,c.width,c.height).data;let x0=c.width,y0=c.height,x1=0,y1=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(a[(y*c.width+x)*4+3]>=64){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x+1);y1=Math.max(y1,y+1);}if(y1<=y0)throw Error('Empty actor');const t=document.createElement('canvas');t.width=x1-x0;t.height=y1-y0;t.getContext('2d').drawImage(c,x0,y0,t.width,t.height,0,0,t.width,t.height);const s=t.toDataURL('image/png');cache.set(key,s);return s;
 }
 function abortAll(){current?.close();if(typeof fieldZone!=='undefined'&&[47,56].includes(fieldZone)&&typeof evActive!=='undefined'&&evActive)evFinish(false);}
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&typeof fieldZone!=='undefined'&&[47,56].includes(fieldZone)&&typeof evActive!=='undefined'&&evActive){e.preventDefault();e.stopImmediatePropagation();abortAll();showScreen('screen-title');}},true);
 function open(zone){
  current?.close();const seq=fieldSeq,root=document.createElement('section');root.id='gradeFourStory';root.dataset.zone=zone;root.dataset.line='0';root.dataset.calm='false';root.dataset.friend='false';
  const orchard=zone===56;
  root.innerHTML='<div class="g4-view"><img class="g4-bg" src="images/'+(orchard?'battle-tate/stage56.webp':'fullart/sado-conversation.webp')+'" alt="'+(orchard?'道沿いに赤いりんごが実る畑':'遠くに島が見える連絡船の船着き場')+'"><div class="g4-cast"><img class="g4-hero" alt="主人公"><img class="g4-mana" alt="マナ"><img class="g4-easy" alt="イージー">'+(orchard?['m-a','f-a','m-b'].map((n,i)=>'<div class="g4-kid k'+i+'"><span>くま</span><img alt="字を読む子ども"></div>').join(''):'')+'</div>'+(orchard?'<div class="g4-sign">ちゅうい</div><div class="g4-kanji dk face-host"><span class="fc">熊</span><span class="face normal"><span class="eyes"><span class="eye"></span><span class="eye"></span></span><span class="mouth"></span></span></div><img class="g4-logo l0" src="images/bust/easy-logo-91.png" alt="丸いマーク"><img class="g4-logo l1" src="images/bust/easy-logo-91.png" alt="丸いマーク">':'<div class="g4-timetable"><b>時こく表</b><span class="g4-letters" aria-label="まだ落ち着かない時刻表の字">時　間　表</span><strong>午後 三時</strong></div>')+'<b class="g4-location">'+(orchard?'りんごばたけ':'さどの しま')+'</b><button class="g4-close">もどる</button></div><div class="g4-dialog"><b class="g4-speaker">マナ</b><div class="g4-slot"></div><span class="g4-next">▼ つづく</span></div>';
  document.body.appendChild(root);const slot=root.querySelector('.g4-slot'),kids=[...root.querySelectorAll('.g4-kid img')];let live=true,ready=false,busy=false,index=0,raf=0,deadline=0,watch=0,smiles=[],walks=[];
  const valid=()=>live&&seq===fieldSeq&&fieldZone===zone&&evActive;
  function restore(){const box=slot.querySelector('#evBox');if(box)$('evOverlay').appendChild(box);}
  function close(){if(!live)return;live=false;clearTimeout(deadline);clearInterval(watch);cancelAnimationFrame(raf);restore();root.remove();if(current===api)current=null;}
  function action(kind){cancelAnimationFrame(raf);busy=true;root.dataset.busy='true';root.dataset.action=kind;const start=performance.now(),duration=kind==='read'?1300:1200,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
   function tick(now){if(!valid())return;const t=reduced?1:Math.min(1,(now-start)/duration);if(kind==='arrive'){kids.forEach((img,i)=>{img.src=t<1?walks[i][Math.floor((now-start)/150)%2]:smiles[i];img.parentElement.style.setProperty('--walk',(1-t)*-75+'cqw');});}else if(kind==='read'){root.dataset.calm=t>=.75?'true':'false';}else root.querySelector('.g4-kanji').style.setProperty('--friend',t);if(t<1)raf=requestAnimationFrame(tick);else{busy=false;root.dataset.busy='false';root.dataset.action='';if(kind==='friend')root.dataset.friend='true';}}
   raf=requestAnimationFrame(tick);
  }
  function line(n,s){if(!live)return;index=n;root.dataset.line=n;root.dataset.easy=(zone===47?n>=2:n>=1)?'true':'false';root.querySelector('.g4-speaker').textContent=(s?.who||EV_SCENES[zone][n]?.who)==='easy'?'イージー':'マナ';if(!ready)return;slot.appendChild($('evBox'));if(orchard){kids.forEach((img,i)=>{img.src=smiles[i];img.parentElement.style.setProperty('--walk','0cqw');});root.dataset.calm=n>=4?'true':'false';root.dataset.friend=n>=5?'true':'false';root.querySelector('.g4-kanji').style.setProperty('--friend',n>=5?1:0);if(n===1)action('arrive');if(n===4)action('read');if(n===5)action('friend');}}
  const api={close,line,busy:()=>busy};current=api;
  root.querySelector('.g4-close').onclick=e=>{e.stopPropagation();abortAll();showScreen('screen-title');};root.querySelector('.g4-dialog').onclick=()=>{if(!busy)evAdvance();};
  deadline=setTimeout(close,4000);watch=setInterval(()=>{if(!valid()||!$('screen-field')?.classList.contains('active'))abortAll();},80);
  const g=heroChar==='girl'?'girl':'boy';const actors=[asset('images/battle-tate/hero-back-'+g+costumeSuffix()+'.webp'),asset('images/sprites/mana-conversation.webp'),asset('images/easy-motion/easy_02_offer/frame-072.webp')];
  if(orchard)for(const name of ['m-a','f-a','m-b'])actors.push(asset('images/sprites/kid-front-'+name+'.webp'),...[0,1].map(row=>asset('images/sprites/kid-scared-'+name+'.webp',2,row,3,2)));
  Promise.all([...[...root.querySelectorAll('.g4-bg,.g4-logo')].map(i=>i.decode()),Promise.all(actors)]).then(async results=>{if(!valid())return;const [h,m,e,...k]=results.at(-1);root.querySelector('.g4-hero').src=h;root.querySelector('.g4-mana').src=m;root.querySelector('.g4-easy').src=e;if(orchard)kids.forEach((img,i)=>{smiles[i]=k[i*3];walks[i]=k.slice(i*3+1,i*3+3);img.src=smiles[i];});await Promise.all([...root.querySelectorAll('.g4-cast img')].map(i=>i.decode()));if(!valid())return;clearTimeout(deadline);ready=true;root.classList.add('ready');line(index,EV_SCENES[zone][index]);}).catch(close);
  return api;
 }
 global.GradeFourStory={openEvent(z,phase){if([47,56].includes(z)&&phase==='in'&&fieldZone===z)return open(z);},eventLine(n,s){current?.line(n,s);},busy(){return current?.busy()||false;},finishEvent(){current?.close();},abort:abortAll,beforeScreen(id){if(id!=='screen-field')abortAll();}};
})(window);
