(function(global){
 'use strict';let current=null;const cache=new Map();
 async function asset(src,col=0,row=0,cols=1,rows=1){
  const key=[src,col,row,cols,rows].join('|');if(cache.has(key))return cache.get(key);const img=new Image();img.src=src;await img.decode();const c=document.createElement('canvas');c.width=Math.floor(img.naturalWidth/cols);c.height=Math.floor(img.naturalHeight/rows);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,col*c.width,row*c.height,c.width,c.height,0,0,c.width,c.height);const a=ctx.getImageData(0,0,c.width,c.height).data;let x0=c.width,y0=c.height,x1=0,y1=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(a[(y*c.width+x)*4+3]>=64){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x+1);y1=Math.max(y1,y+1);}if(y1<=y0)throw Error('Empty actor');const t=document.createElement('canvas');t.width=x1-x0;t.height=y1-y0;t.getContext('2d').drawImage(c,x0,y0,t.width,t.height,0,0,t.width,t.height);const s=t.toDataURL('image/png');cache.set(key,s);return s;
 }
 function start(done,fallback){
  if(fieldZone!==44||EvCutScene.isActive())return false;current?.abort();const seq=fieldSeq;stopAutoExplore();heroLock=true;const root=document.createElement('section');root.id='nangokuStory';root.dataset.phase='loading';
  root.innerHTML='<div class="ng-view"><img class="ng-bg" src="images/battle-tate/stage44.webp" alt="ヤシと青い海に沿って出口へ続く道"><div class="ng-cast"><img class="ng-man" alt="出口へ去る笠の男の背中"><img class="ng-hero" alt="背中を追う主人公"><img class="ng-mana" alt="主人公と追うマナ"></div><b class="ng-location">なんごくの まち</b><button class="ng-close">もどる</button></div><div class="ng-dialog"><b>マナ</b><p class="ng-text"></p><span>▼ つづく</span></div>';document.body.appendChild(root);
  const man=root.querySelector('.ng-man'),hero=root.querySelector('.ng-hero'),mana=root.querySelector('.ng-mana'),text=root.querySelector('.ng-text');let live=true,ready=false,busy=true,index=-1,raf=0,timer=0,deadline=0,watch=0,old=false;let men=[],heroes=[],manas=[];
  const valid=()=>live&&seq===fieldSeq&&fieldZone===44&&$('screen-field')?.classList.contains('active');
  function clean(){clearTimeout(timer);clearTimeout(deadline);clearInterval(watch);cancelAnimationFrame(raf);document.removeEventListener('keydown',key,true);root.remove();stopBattleHakaseVoice();}
  function finish(){if(!valid())return;live=false;clean();heroLock=false;if(current===api)current=null;done();}
  function abort(){if(!live)return;live=false;clean();heroLock=false;if(current===api)current=null;if(old&&EvCutScene.isActive())EvCutScene.skip();}
  function failed(){if(old)return;if(!valid()){abort();return;}clearTimeout(deadline);root.remove();old=true;fallback(()=>{if(valid())finish();});}
  function key(e){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();abort();showScreen('screen-title');}}
  function animate(chase,after){busy=true;root.dataset.busy='true';root.dataset.phase=chase?'chase':'depart';const view=root.querySelector('.ng-view').getBoundingClientRect(),fromBottom=(view.bottom-man.getBoundingClientRect().bottom)/view.height*100;const start=performance.now(),duration=chase?1600:1800,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
   function tick(now){if(!valid())return;const t=reduced?1:Math.min(1,(now-start)/duration),f=Math.floor((now-start)/150);if(chase){hero.src=heroes[f%2];mana.src=manas[f%2];for(const [el,x]of [[hero,27],[mana,52]]){el.style.left=(x+(el===hero?27:20)*t)+'%';el.style.bottom=(6+34*t)+'%';el.style.setProperty('--scale',1-.42*t);}}else{man.src=men[[0,1,2,1][f%4]];const bg=root.querySelector('.ng-bg').getBoundingClientRect(),v=root.querySelector('.ng-view').getBoundingClientRect(),exitBottom=100-(bg.top-v.top+bg.height*380/1536)/v.height*100;man.style.left=(68+57*t)+'%';man.style.bottom=(fromBottom+(exitBottom-fromBottom)*t)+'%';man.style.setProperty('--scale',1-.38*t);}if(t<1)raf=requestAnimationFrame(tick);else{busy=false;root.dataset.busy='false';if(!chase){man.style.visibility='hidden';root.dataset.phase='waiting';}after?.();}}
   raf=requestAnimationFrame(tick);
  }
  function next(){if(!valid()||!ready||busy)return;clearTimeout(timer);index++;if(index>=3){text.textContent='';stopBattleHakaseVoice();animate(true,finish);return;}const ln=EV_CUT_SCENES.nangoku44.cuts[index];root.dataset.line=index;root.dataset.phase='notice';text.innerHTML=global.talkText?global.talkText(ln.text,44):ln.text;playBattleHakaseVoice(ln.snd);if(index===2)animate(false);timer=setTimeout(next,Math.min(Math.max(ln.text.length*350+1000,4000),10000));}
  const api={abort};current=api;root.querySelector('.ng-close').onclick=e=>{e.stopPropagation();abort();showScreen('screen-title');};root.querySelector('.ng-dialog').onclick=next;document.addEventListener('keydown',key,true);watch=setInterval(()=>{if(!valid())abort();},80);deadline=setTimeout(failed,4000);
  const gender=heroChar==='girl'?'girl':'boy',sheet=heroSheetUrl();
  Promise.all([root.querySelector('.ng-bg').decode(),...[0,1,2].map(col=>asset('images/sprites/maro-back-walk3.webp',col,0,3,1)),...[0,1].map(row=>asset(sheet,1,row,3,2)),...['a','b'].map(p=>asset('images/mana-back-'+p+'.webp'))]).then(async ([,m0,m1,m2,h0,h1,a,b])=>{if(!valid()||old)return;men=[m0,m1,m2];heroes=[h0,h1];manas=[a,b];man.src=m1;hero.src=h1;mana.src=b;await Promise.all([man,hero,mana].map(i=>i.decode()));if(!valid()||old)return;clearTimeout(deadline);ready=true;busy=false;root.dataset.busy='false';root.classList.add('ready');next();}).catch(failed);
  return true;
 }
 global.NangokuStory={start,abort(){current?.abort();},beforeScreen(id){if(id!=='screen-field')current?.abort();}};
})(window);
